# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5a42c24389b6374a029224799a64b20e9c9d3a9c8d73a475a00463771825f68458d6dc65d07c9633c23e27d0daad465d0e3dddef4e513d4fe3b862889825b4c

test:
  secret_key_base: a8c96d9e5f2e613d5857b32f28250bdee996bcc0bc49cd9dd2e12dcf89ad89ce183f09cc099c6e2c7dec35469398debd84798280e0d1d436e57374e76264b33f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
